---
title: About
site: distill::distill_website
output:
  distill::distill_article
---

## Education

Swinburne University of Technology | Doctor of Philosophy in Social Psychology | 2010

Swinburne University of Technology | Bachelor of Arts Psychology (Honours) | 2003

La Trobe University | Bachelor of Behavioural Science | 2001

## Media

I provide media comment on research and stories relating to conspiracy theories. Selected media engagements include [newspaper](https://www.theguardian.com/science/2022/apr/19/in-a-pandemic-of-medical-misinformation-how-do-you-deal-with-conspiracy-believers), [podcasts](https://www.abc.net.au/radionational/programs/rearvision/medical-conspiracy-theories-through-the-ages/13649988), [television appearances](https://www.abc.net.au/news/2021-06-15/why-do-people-buy-into-conspiracy-theories-like-qanon/13388796), and [radio](https://www.abc.net.au/triplej/programs/hack/hack/13535808).

My colleagues and I have also written for [The Conversation](https://theconversation.com/was-phar-lap-killed-by-gangsters-new-research-shows-which-conspiracies-people-believe-in-and-why-158610).

## Memberships

Member of the [Society of Australasian Social Psychologists](https://sasp.org.au) | 2004 - present

Member of the [Society for Personality and Social Psychology](https://spsp.org) | 2016 - present

The [Society of Australasian Social Psychologists](https://sasp.org.au) executive: Communication officer | 2016 - present

Member of the [International Society of Political Psychology](https://ispp.org) | 2020 - present

Member of [National Centre for Immunisation Research and Surveillance](https://ncirs.org.au) Social Science Advisory Group | 2020 - present

Member of [Australasian Society of Behavioural Health and Medicine](https://www.asbhm.com) | 2021 - present

Editorial board of [The Journal of Social Psychology](https://www.tandfonline.com/journals/vsoc20) | 2022 – present