---
title: Publications
output:
  distill::distill_article:
    toc: true
---

<script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
<script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

## Conspiracy Theories

<div style="display: flex">
**Marques, M.D.**, Williams, M.N., Clarke, E.J.R., Fida, N., Heffernan, J., Hill, S.R., Kerr, J.R., Ling, M., Parkinson, C., Thermos, M., & Tier, J. (accepted 8 December 2025). Testing the socio-functional model: Does precarity cause conspiracy belief? *British Journal of Social Psychology*.
[[preprint PDF]](https://osf.io/nq3y7/files/d2qe5)
*Impact Factor = 3*
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="" data-hide-no-mentions="true" class="altmetric-embed"></div>

<span class="__dimensions_badge_embed__" data-doi="" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

</div>

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
  <font size="3">Research seeking to explain why people believe conspiracies has largely focused on intrapsychic factors, but there is growing research examining structural level elements of disadvantage. The socio-functional model of conspiracy belief (Adam-Troian et al., 2023) posits that subjective feelings of permanent insecurity arising from objective material strain (i.e., precarity) causes conspiracy belief directly or indirectly through institutional distrust. Across three preregistered studies using observational longitudinal designs over 3 (*n* = 637) and 11 months (*n* = 832), and a between-groups experimental design (*n* = 285), we use various methods to estimate causal effects for this proposition during the current cost-of-living crisis. In Studies 1 and 2 using random intercept cross-lagged panel models we find no evidence that increases in precarity temporally precede increases in conspiracy belief (or vice-versa), but find stable between-persons effects over time. In Study 3, despite successfully manipulating precarity using a self-imagine paradigm, we find no direct or indirect effect on conspiracy belief through decreased government trust. We discuss the importance of using methods that permit credible causal inferences, and key directions for future studies investigating the socio-functional model.</font>
</details>

<br>

<div style="display: flex">
**Marques, M.D.** (2025). Patient autonomy in decision-making is more than individual belief: Understanding why health misinformation and conspiracy theories are so appealing. *Patient Education and Counseling, 139*, 109233. [https://doi.org/10.1016/j.pec.2025.109233](https://doi.org/10.1016/j.pec.2025.109233)
[[PDF]](https://doi.org/10.31234/osf.io/mxthu_v1)
*Impact Factor = 2.9*
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="10.1016/j.pec.2025.109233" data-hide-no-mentions="true" class="altmetric-embed"></div>

<span class="__dimensions_badge_embed__" data-doi="10.1016/j.pec.2025.109233" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

</div>

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
  <font size="3"> We live in a world filled with more information that is easier to access than ever before. Over 20 years ago, approximately 5% of all online searches related to health or medical information [1]. More recently in 2017, nearly 75% of Americans used the internet as their primary source for medical and health information [2], and approximately 50% of Australian emergency department patients went online to search for health-related information [3]. In Patient Education and Counselling, Rubinelli [4] offers a thoughtful discussion piece that considers the risk to patient autonomy in an online world filled with health (mis)information.</font>
</details>

<br>

<div style="display: flex">

Toribio-Florez, D., Altenmuller, M.S., Douglas, K.M., Gollwitzer, M., Adinugroho, I., …, **Marques, M.D.**, …, & Wojcik, D. (2025). Victims of conspiracies? A cross-national examination of the relationship between conspiracy beliefs and victim justice sensitivity. *European Journal of Social Psychology*. 
[https://doi.org/10.1002/ejsp.70008](https://doi.org/10.1002/ejsp.70008)
[[PDF]](https://osf.io/bjkph_v2/)<br>
*Impact Factor = 2.22*
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="10.1002/ejsp.70008" data-hide-no-mentions="true" class="altmetric-embed"></div>

<span class="__dimensions_badge_embed__" data-doi="10.1002/ejsp.70008" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

</div>

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
  <font size="3"> Conspiracy beliefs have been linked to perceptions of collective victimhood. We adopt an individual perspective on victimhood by investigating the relationship between conspiracy beliefs and the individual disposition to perceive and react to injustice as a victim (i.e., victim justice sensitivity; VJS). Data from two German samples (*Ns* = 370, 373) indicated a positive association between VJS and conspiracy mentality beyond conceptually related covariates (e.g., mistrust). In a multinational sample from 15 countries (*N* = 14,978), VJS was positively associated with both general and specific conspiracy beliefs (about vaccines and climate change) within countries, though these associations varied across countries. However, economic, sociopolitical, and cultural country-level factors that might explain the cross-country variability (e.g., GDP, Human Freedom Index, Individualism-Collectivism), including indices of collective exposure to direct violence, did not moderate the studied associations. Future research should investigate the association between victimhood and conspiracy beliefs considering both intraindividual and intergroup perspectives.</font>
</details>

<br>

<div style="display: flex">
Williams, M.N., **Marques, M.D.**, Kerr, J.R., Hill, S.R., Ling, M., & Clarke, E.J.R. (2025). Does developing a belief in one conspiracy theory lead a person to be more likely to believe in others? *European Journal of Social Psychology, 55*(4), 554-564.
[https://doi.org/10.1002/ejsp.3153](https://doi.org/10.1002/ejsp.3153)
[[PDF]](https://osf.io/qpgvh_v1)<br>
*Impact Factor = 2.22*
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="10.1002/ejsp.3153" data-hide-no-mentions="true" class="altmetric-embed"></div>

<span class="__dimensions_badge_embed__" data-doi="10.1002/ejsp.3153" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

</div>

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
  <font size="3">The monological belief system model (Goertzel, 1994) suggests that—for at least a subset of people—developing a belief in one conspiracy theory will *cause* them to be more likely to believe in others. This model has been influential in the literature, but its core causal hypothesis has never been credibly tested. We therefore tested it in two longitudinal studies. Study 1 used a sample from New Zealand and Australia (*N* = 498), with 7 monthly waves. Study 2 (preregistered) used a sample from New Zealand, Australia and the United Kingdom (*N* = 978), with 13 monthly waves. We applied random intercept cross-lagged panel models, permitting a credible causal identification strategy, albeit we cannot rule out time-varying confounds. We find that increased belief in a conspiracy theory at one wave did (on average) lead to increased belief in other conspiracies at the next wave, although the estimated effects were small.</font>
</details>

<br>

<div style="display: flex">

**Marques, M.D.**, Kerr, J.R., Stukas, A.A., & McLennan, J. (2024). The Effect of Scientific Conspiracy Theories on Scepticism Towards Biotechnologies. *Public Understanding of Science, 34*(5), 646-664.
[https://doi.org/10.1177/09636625241300896](https://journals.sagepub.com/doi/10.1177/09636625241300896)
[[PDF]](https://osf.io/preprints/psyarxiv/y6hj2)<br>
*Impact Factor = 3.5*
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="10.1177/09636625241300896" data-hide-no-mentions="true" class="altmetric-embed"></div>

<span class="__dimensions_badge_embed__" data-doi="10.1177/09636625241300896" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

</div>

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
  <font size="3">Many conspiracy theories implicate scientists and science. We investigated the impact of exposure to scientific conspiracies about biotechnologies. Across three pre-registered online studies (*Ns*=1,000), participants who read information about conspiracies involving agribiotechnology companies or biobank scientists were more likely to endorse conspiracies. Other effects of exposure to conspiracy information were mixed. In Study 1, reading about an agricultural biotechnology conspiracy had a small significant effect on reducing intentions to eat Genetically Modified food. In Study 2, exposure to a conspiracy involving biobank scientists decreased support for biobanks, mediated by decreased trust in biobank scientists. In Study 3, this conspiracy had no effect on wider beliefs of the role of science in society (science populism), nor support of Genetically Modified food-promoting policies. Overall, we found that exposure to conspiracies involving scientific claims increased conspiracy belief endorsement and can further negative effects. However, the effects of conspiracies on science populism appears limited</font>
</details>

<br>

<div style="display: flex">

Albath, E.A., Greifeneder, R., Douglas, K.M., Cichocka, A., **Marques, M.D.**, Wilson, M.S., Kerr, J.R., Sibley, C.G., & Osborne, D. (2024). Does Lower Psychological Need Satisfaction Foster Conspiracy Belief? Longitudinal Effects Over Three Years in New Zealand. *Personality and Social Psychology Bulletin*.
[https://doi.org/10.1177/01461672241292841](https://journals.sagepub.com/doi/10.1177/01461672241292841)
[[PDF]](https://doi.org/10.1177/01461672241292841)<br>
*Impact Factor = 3.4*
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="10.1177/01461672241292841" data-hide-no-mentions="true" class="altmetric-embed"></div>

<span class="__dimensions_badge_embed__" data-doi="10.1177/01461672241292841" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

</div>

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
  <font size="3">Although conspiracy belief may arise from a motivation to restore psychological needs, research has yet to investigate the relationship between psychological need satisfaction and conspiracy belief over time. Using three annual waves of panel data in New Zealand (2019-2022; *N* = 50,505), we examined the relationship between conspiracy belief and four psychological needs (namely, belonging, control, meaning in life, and self-esteem). Results from a random-intercept cross-lagged panel model revealed stable between-person effects indicating that those whose core needs are generally unmet tend to exhibit higher levels of conspiracy belief. The within-person associations further demonstrate that the frustration of control and belonging needs temporally precede increases in conspiracy belief, but these cross-lagged associations vary across waves and may depend on external factors (e.g., the  start of a pandemic). These data provide novel insights into the psychological factors that foster conspiracy belief and suggest that within-person longitudinal associations may be context-dependent.</font>
</details>

<br>

<div style="display: flex">

Williams, M.N. Ling, M., Kerr, J.R., Hill, S.R., **Marques, M.D.**, Mawson, H., & Clarke, E.J.R. (2024). People do change their beliefs about conspiracy theories—but not often. *Scientific Reports, 14*, 3836.
[https://doi.org/10.1038/s41598-024-51653-z](https://www.nature.com/articles/s41598-024-51653-z)
[[PDF]](https://psyarxiv.com/5q2ky/)<br>
*Impact Factor = 4.6*
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="10.1038/s41598-024-51653-z" data-hide-no-mentions="true" class="altmetric-embed"></div>

<span class="__dimensions_badge_embed__" data-doi="10.1038/s41598-024-51653-z" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

</div>

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
  <font size="3">Recent research has produced a significant body of knowledge about the antecedents and consequences of individual differences in belief in conspiracy theories. What is less clear, however, is the extent to which individuals’ beliefs in conspiracy theories vary over time (i.e., *within-person* variation). In this descriptive and exploratory study, we therefore aimed to describe within-person variability in belief in conspiracy theories. We collected data from 498 Australians and New Zealanders using an online longitudinal survey, with data collected at monthly intervals over 6 months (March to September 2021). Our measure of conspiracy theories included items describing ten conspiracy theories with responses on a 5-point Likert scale. While there was substantial between-person variance, there was much less within-person variance (intraclass *r* = 0.91). This suggests that beliefs in conspiracy theories were highly stable in our sample. This stability implies that longitudinal studies testing hypotheses about the causes and consequences of belief in conspiracy theories may require large samples of participants and time points to achieve adequate power. It also implies that explanations of belief in conspiracy theories need to accommodate the observation that beliefs in such theories vary much more between people than within people.</font>
</details>

<br>

<div style="display: flex">

Coelho, P., Foster, K., Nedri, M., & **Marques, M.D.** (2022). Increased belief in vaccination conspiracy theories predicts increases in vaccination hesitancy and powerlessness: Results from a longitudinal study. *Social Science & Medicine, 315*, 115522.
[https://doi.org/10.1016/j.socscimed.2022.115522](https://www.sciencedirect.com/science/article/pii/S0277953622008280)
[[PDF]](https://psyarxiv.com/gx58v/)<br>
*Impact Factor = 5.379*
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="10.1016/j.socscimed.2022.115522" data-hide-no-mentions="true" class="altmetric-embed"></div>

<span class="__dimensions_badge_embed__" data-doi="10.1016/j.socscimed.2022.115522" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

</div>

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
  <font size="3">*Rationale*: Vaccinations are an important part of a public health strategy against preventable diseases, and uptake is influenced by factors including hesitancy. The belief of vaccine related misinformation including anti-vaccination conspiracy theories has been found to be associated with increased vaccine hesitancy.
  *Objective*: While research suggests that these conspiracy theory beliefs may arise to satisfy unmet needs such as restoring loss of personal control, somewhat ironically these anti-vaccination conspiracy theories may frustrate these needs. This study examined the causal relationships between vaccination hesitancy, vaccination conspiracy theories, and vaccination related powerlessness.
  *Methods*: Using a stationary random intercepts cross lagged panel model, we investigated the temporal ordering of vaccination hesitancy, powerlessness, and vaccination conspiracy theory beliefs in a sample of Australian adults (N = 500) in a longitudinal study with 5-timepoints over 4-months between June and October 2021.
  *Results*: Results from a random intercept cross-lagged model, that separates between-person stability from within-person change, suggested that increased belief in vaccination conspiracy theories was associated with future increases in vaccination hesitancy and powerlessness (but not vice versa). Findings also showed that increases in vaccination hesitancy and conspiracy theory beliefs predicted respective increases from a person’s trait-level mean at subsequent timepoints.
  *Conclusions*: Vaccination conspiracy theories appear to increase vaccination powerlessness and hesitancy, rather than satisfying an unmet need for personal control.</font>
</details>

<br>

<div style="display: flex">

**Marques, M.D.**, Hill, S.R., Clarke, E.J.R., Williams, M.N., Ling, M., Kerr, J.R., Douglas, K.M., Cichocka,
A., & Sibley, C.G. (2022). Democracy and belief in conspiracy theories in
New Zealand. *Australian Journal of Political Science, 57*(3), 264-279. [https://doi.org/10.1080/10361146.2022.2122773](https://www.tandfonline.com/doi/full/10.1080/10361146.2022.2122773) [[PDF]](https://psyarxiv.com/s8qf4/)<br>
*Impact Factor = 1.2*
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="10.1080/10361146.2022.2122773" data-hide-no-mentions="true" class="altmetric-embed"></div>

<span class="__dimensions_badge_embed__" data-doi="10.1080/10361146.2022.2122773" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

</div>

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
  <font size="3">The COVID-19 pandemic supercharged the spread of fake news, misinformation, and conspiracy theories worldwide. Using a national probability sample of adults fromthe New Zealand Attitudes and Values Study during 2020 (17–99 years old; *M* = 48.59, *SD* = 13.86; 63% women, 37% men; *N* = 41,487), we examined the associations between agreement with general conspiracy beliefs and political indicators of intention to vote and satisfaction with government, alongside political factors includingtrust in politicians, political efficacy, identity centrality, and political ideology. Left-wing political ideology, trust in politicians, and political efficacy accounted for most of the explained variance in satisfaction with the government. General conspiracy belief was also a unique contributor to lower satisfaction with the government. We also found a curvilinear relationship between political ideology with heightened belief in conspiracies at both ideological extremes and the centre. Findings are discussed in terms of the consequences of conspiracy belief on democratic engagement.</font>
</details>

<br>

<div style="display: flex">

Jolley, D., **Marques, M.D.**, Cookson, D. (2022). Shining a spotlight on the dangerous consequences of
conspiracy theories. Special issue in *Current Opinion in Psychology, 47*, 101363. [https://doi.org/10.1016/j.copsyc.2022.101363](https://www.sciencedirect.com/science/article/pii/S2352250X22000823) [[PDF]](https://www.sciencedirect.com/science/article/pii/S2352250X22000823/pdfft?md5=dfc9f1758690aabb2b0a34f5690c5723&pid=1-s2.0-S2352250X22000823-main.pdf)<br>
*Impact Factor = 6.813*
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="10.1016/j.copsyc.2022.101363" data-hide-no-mentions="true" class="altmetric-embed"></div>

<span class="__dimensions_badge_embed__" data-doi="10.1016/j.copsyc.2022.101363" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

</div>
<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
  <font size="3">The COVID-19 pandemic has illuminated how conspiracy beliefs–that explain important events as the secret actions of the powerful–can severely impact health choices (such as reduced infection-prevention behaviours). However, the consequences of conspiracy beliefs span far beyond the topic of COVID-19. This review shines a spotlight on how conspiracy beliefs could impact public and personal health (e.g., vaccine uptake), democratic citizenship (e.g., political engagement), intergroup relations (e.g., prejudice and discrimination), and may inspire violence and extremism. We argue that conspiracy beliefs are likely to have the power to mobilise citizens in ways detrimental to a smooth-running society. We conclude the review by offering a range of fruitful avenues for future investigation.</font>
</details>

<br>

<div style="display: flex">

**Marques, M.D.**, Douglas, K.M., & Jolley, D. (2022). Practical recommendations to communicate with
patients about health-related conspiracy theories. *The Medical Journal of Australia, 216*(8),
381-384. [https://doi.org/10.5694/mja2.51475](https://onlinelibrary.wiley.com/doi/10.5694/mja2.51475) [[PDF]](https://onlinelibrary.wiley.com/doi/pdf/10.5694/mja2.51475)<br>
*Impact Factor = 7.738*
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="10.5694/mja2.51475" data-hide-no-mentions="true" class="altmetric-embed"></div>

<span class="__dimensions_badge_embed__" data-doi="10.5694/mja2.51475" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

</div>

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
  <font size="3">Health-related conspiracy theories often advance the argument that information is being kept secret from the public by powerful individuals or groups within the government or health industry. They are widespread and are associated with important health attitudes, intentions, and behaviours. Recent research suggests that individuals are attracted to conspiracy theories to satisfy three important and fundamental psychological needs: epistemic, existential, and social needs. Understanding these underlying motivations associated with health-related conspiracy theories can help address patients’ beliefs. Debunking and inoculation are discussed as approaches that can be used to address patients’ belief in health-related conspiracy theories.</font>
</details>

<br>

<div style="display: flex">

**Marques, M.D.**, Ling, M., Williams, M.N., Kerr, J.R., & McLennan, J. (2022). Australasian public
awareness and belief in conspiracy theories: Motivational correlates. *Political Psychology,
43*(1), 177-198. [https://doi.org/10.1111/pops.12746](https://onlinelibrary.wiley.com/doi/10.1111/pops.12746) [[PDF]](https://psyarxiv.com/vr896/)<br>
*Impact Factor = 4.333*
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="10.1111/pops.12746" data-hide-no-mentions="true" class="altmetric-embed"></div>

<span class="__dimensions_badge_embed__" data-doi="10.1111/pops.12746" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
  <font size="3">Belief in conspiracies is not restricted to the fringe dwellers of society. International research suggests that such beliefs are quite common and that conspiracy theories may serve three basic psychological motives (i.e., epistemic, existential, and relational) for individuals. Yet, little is known about conspiracy theory awareness or belief in Australasia. We report the first large systematic investigation of system justifying motives using twonationally representative samples of Australians (*n* = 1,011) and New Zealanders (*n* = 754). Our findings show that almost all are aware of local and international conspiracies, the majority endorse one or more, and that all three psychological motives consistently relate to conspiracy belief, but not to awareness. In a series of hierarchical multiple regressions, we find that relational (i.e., increased anomie and disillusionment with the government) and existential motives (i.e., less trust in others and increased religiosity) are uniquely and relatively more important than epistemic needs (i.e., decreased analytic thinking) as predictors of increased local and international conspiracy belief. Findings are discussed in terms of the importance of understanding conspiracy theories as an ideological belief system that may function to serve underlying psychological motives.</font>
</details>

<br>

<div style="display: flex">

Williams, M.N., **Marques, M.D.**, Hill, S.R., Kerr, J.R., & Ling, M. (2022). Why are beliefs in different conspiracy theories positively correlated across individuals? Testing monological network vs. unidimensional factor model explanations. Registered report. *British Journal of Social Psychology, 61*(3), 1011-1031. [https://doi.org/10.1111/bjso.12518](https://bpspsychub.onlinelibrary.wiley.com/doi/10.1111/bjso.12518) [[PDF]](https://psyarxiv.com/xyf46/)<br>
*Impact Factor = 4.691*
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="10.1111/bjso.12518" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1111/bjso.12518" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
  <font size="3">A substantial minority of the public express belief in conspiracy theories. A robust phenomenon in this area is that people who believe one conspiracy theory are more likely to believe in others. But the reason for this “positive manifold” of belief in conspiracy theories is unclear. One possibility is that a single underlying latent factor (e.g., “conspiracism”) causes variation in belief in specific conspiracy theories. Another possibility is that beliefs in various conspiracy theories support one another in a mutually reinforcing network of beliefs (the “monological belief system” theory). While the monological theory has been influential in the literature, the fact that it can be operationalised as a statistical network model has not previously been recognised . In this study, we therefore tested both the unidimensional factor model and the monological/network model. Participants were 1553 American adults recruited via Prolific. Belief in conspiracies was measured using an adapted version of the Belief in Conspiracy Theories Inventory. The fit of the two competing models was evaluated both by using van Bork et al.’s (2018, 2019) method for testing network vs. unidimensional factor models, as well as by evaluating goodness of fit to the sample covariance matrix. In both cases, evaluation of fit according to our preregistered inferential criteria favoured the network model. This finding is consistent with the monological belief system theory, and inconsistent with a unidimensional factor model explanation.</font>
</details>

<br>

<div style="display: flex">

**Marques, M.D.**, Kerr, J.R., Williams, M.N., Ling, M., & McLennan, J. (2021). Associations between
conspiracism and the rejection of scientific innovations. *Public Understanding of Science, 30*(7), 854-867. [https://doi.org/10.1177/09636625211007013](https://journals.sagepub.com/doi/10.1177/09636625211007013) [[PDF]](https://psyarxiv.com/y9mnb/)<br>
*Impact Factor = 3.702*
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="10.1177/09636625211007013" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1177/09636625211007013" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
  <font size="3">Public opinion regarding scientific developments such as genetically modified (GM) food canbe mixed. We suggest such science-based technological innovations are rejected by some because they are perceived to be advanced as part of a conspiracy. In nationally representative samples (Australia *n* = 1,011; New Zealand *n* = 754) we report the associations between five conspiracism facets and anti-science attitudes. Results indicate broad public opposition to GM food and use of nuclear power, but more acceptance of renewable power, potable recycled water, 5G networks, and childhood vaccinations. There were small to moderate associations between the rejection of scientific innovations and conspiracism. Multivariate models estimating unique associations of conspiracism facets with anti-science attitudes suggested several novel and important relationships, particularly for childhood vaccination, GM food, and 5G networks. We discuss the importance of examining factors such as conspiracism in understanding what may motivate and sustain rejection of scientific evidence-based claims about socially contentious technological innovations.</font>
</details>

<br>

<div style="display: flex">

Natoli, E.E., & **Marques, M.D.** (2021). The antidepressant hoax: Conspiracy theories decrease health-seeking intentions. *British Journal of Social Psychology, 60*(3), 902-923. [https://doi.org/10.1111/bjso.12426](https://bpspsychub.onlinelibrary.wiley.com/doi/10.1111/bjso.12426) [[PDF]](https://psyarxiv.com/8aedm/)<br>
*Impact Factor = 4.691*
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="10.1111/bjso.12426" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1111/bjso.12426" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
  <font size="3">Health-related conspiracy theories can undermine the trustworthiness of actors and institutions and may impact an individual’s intention to seek help. Across 3 experimental studies we investigated the consequences of exposure to an antidepressant conspiracy theory on general intentions to seek medical and psychological help. Study 1 participants (*N* = 299) were randomly allocated to read one of three articles (pro-conspiracy, anti-conspiracy, control) after which they completed measures of conspiracy endorsement, trust, powerlessness and health-seeking intentions. Results suggested that exposure to antidepressant conspiracy theories significantly reduced individual’s intention to seek help indirectly through decreased trust in health authorities, but not health-industry related powerlessness. In two additional pre-registered studies we found some support for these findings. While Study 2 (*N* = 244) found no support for a direct or indirect relationship between conspiracy exposure and health-seeking intentions, an exploratory analysis highlighted the importance of gender differences when investigating conspiracy exposure on intentions. Study 3 (*N* = 247) replicated Study 1 findings, highlighting that antidepressant conspiracy theories decrease health-seeking intentions indirectly through decreased trust and increased powerlessness. Mere exposure to antidepressant conspiracy theories had significant indirect consequences on general health-seeking intentions.</font>
</details>

## Science attitudes

<div style="display: flex">
Mede, N.G., Cologna, V., Berger, S., Besley, J., Brick, C., Joubert, M., …, **Marques, M.D.**, …, & Zwaan, R.A. (2025). Public communication about science in 68 countries: Global evidence on how people encounter information about science and engage with it. *Science Communication*, 1-46. [https://doi.org/10.1177/10755470251376615](https://journals.sagepub.com/doi/10.1177/10755470251376615)[[PDF]](https://journals.sagepub.com/doi/pdf/10.1177/10755470251376615?download=true)<br> 
*Impact Factor = 4.1*
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="10.1177/10755470251376615" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1177/10755470251376615" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
  <font size="3">This 68-country survey (*n* = 71,922) examines science information diets and communication behavior, identifies cross-country differences, and tests how such differences are associated with sociopolitical and economic conditions. We find that social media are the most used sources of science information in most countries, except those with democratic-corporatist media systems where news media tend to be used more widely. People in collectivist societies are less outspoken about science in daily life, whereas lower education is associated with higher outspokenness. Limited access to digital media is correlated with participation in public protests on science matters. We discuss implications for future research, policy, and practice.
</font>
</details>

<br>

<div style="display: flex">
Cologna, V., Meiler, S., Kropf, C.M., Lüthi, S., Mede, N.G., Bresch, D.N., …, **Marques, M.D.**, … et al. (2025). Extreme weather event attribution predicts climate policy support across the world. *Nature Climate Change, 15*, 725–735. [https://doi.org/10.1038/s41558-025-02372-4](https://www.nature.com/articles/s41558-025-02372-4#Abs1)[[PDF]](https://www.nature.com/articles/s41558-025-02372-4.pdf)<br> 
*Impact Factor = 27.1*
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="10.1038/s41558-025-02372-4" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1038/s41558-025-02372-4" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
  <font size="3">Extreme weather events are becoming more frequent and intense due to climate change. Yet, little is known about the relationship between exposure to extreme events, subjective attribution of these events to climate change, and climate policy support, especially in the Global South. Combining large-scale natural and social science data from 68 countries (*N* = 71,922), we develop a measure of exposed population to extreme weather events and investigate whether exposure to extreme weather and subjective attribution of extreme weather to climate change predict climate policy support. We find that most people support climate policies and link extreme weather events to climate change. Subjective attribution of extreme weather was positively associated with policy support for five widely discussed climate policies. However, exposure to most types of extreme weather event did not predict policy support. Overall, these results suggest that subjective attribution could facilitate climate policy support.
</font>
</details>

<br>

<div style="display: flex">
Stanley, S.K., Ghasemi, O., Kerr, J.R., Ross, R.M., **Marques, M.D.**, Mede, N.M., Berger, S., Alfano, M., Levy, N., Ferreiram M., & Cologna, V. (2025). Community attitudes towards advancing climate justice with climate aid. *Journal of Environmental Psychology, 106*, 102679. [https://doi.org/10.1016/j.jenvp.2025.102679](https://www.sciencedirect.com/science/article/pii/S0272494425001628)[[PDF]](https://www.sciencedirect.com/science/article/pii/S0272494425001628/pdfft?md5=2cd8812f568cc4020504ba879cfb8170&pid=1-s2.0-S0272494425001628-main.pdf)<br> 
*Impact Factor = 7.0*
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="10.1016/j.jenvp.2025.102679" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1016/j.jenvp.2025.102679" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
  <font size="3">Research on support for climate policies has predominantly focused on support for mitigation policies. Research remains scarce on public support for climate aid policy (i.e., adaptation policies that direct support to those most affected by climate change). The justice implications of unmitigated climate change loom large, yet it is currently unclear to what extent people view climate change as an inequality issue. To investigate this, we surveyed participants from the United Kingdom (*n* = 531), United States (*n* = 528), Australia (*n* = 1450), and New Zealand (*n* = 1022) on attitudes about climate change inequality, experiences of climate emotions, support for climate aid policy, as well as their political orientation. Those who reported greater agreement that climate change is an inequality issue also reported experiencing more intense negative emotions about climate change and greater support for climate aid policy. We propose a theoretical model whereby political conservatives are less likely to see climate change as an inequality issue, which could account for their lower support for climate aid policy and their more muted emotional response to climate change. We find preliminary support for this model using mediation analyses. Our findings suggest that in these four nations, beliefs about the inequality in who causes climate change and who suffers its worst consequences may be relevant to community support for the implementation of climate aid policy.
</font>
</details>

<br>

<div style="display: flex">
Ghasemi, O., Cologna, V., Mede, N.G., Stanley, S.K., Strahm, N., Ross, R., Alfano, M., Kerr, J.R, **Marques, M.D.**, Berger, S., Besley, J.C., Brick, C., Joubert, M., Maibach, E., Mihelj, S., Newell, B.R., Oreskes, N., & Schäfer, M.S. (2025). Gaps in public trust between scientists and climate scientists: a 68 country study. *Environmental Research Letters, 20*(6), 061002.
[https://doi.org/10.1088/1748-9326/add1f9](https://iopscience.iop.org/article/10.1088/1748-9326/add1f9) [[PDF]](https://iopscience.iop.org/article/10.1088/1748-9326/add1f9/pdf)<br>
*Impact Factor = 5.8*
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="10.1088/1748-9326/add1f9" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1088/1748-9326/add1f9" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
  <font size="3">This study compares public trust in climate scientists and scientists in general across 68 countries (*N* = 69,534). On average, participants reported moderately high levels of trust in climate scientists, with trust levels being slightly lower than trust in scientists in general. Overall, this trust gap was larger among participants who identified as politically conservative or right-leaning, but there was considerable variation across countries
</font>
</details>

<br>

<div style="display: flex">

Stanley, S.K., Ghasemi, O., Ross, R.M., Kerr, J.K., **Marques, M.D.**, Alfano, M., Levy, N., Ferreira, M., Cologna, V., Mede, N.G., & Berger, S. (2025). Anticipatory solastalgia in the Antipodes: Evidence of future-oriented distress about environmental change in Australia and New Zealand. *The Journal of Climate Change and Health, 23,* 100415. 
[https://doi.org/10.1016/j.joclim.2025.100415](https://www.sciencedirect.com/science/article/pii/S2667278225000057/)<br>
*CiteScore = 4.8*
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="10.1016/j.joclim.2025.100415" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1016/j.joclim.2025.100415" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
  <font size="3">*Introduction*: Lived experience of negative environmental change can evoke distress called ‘solastalgia’. Worldwide, people are reporting emotional challenges relating to awareness of current and continued environmental decline, even without a lived direct experience of climate change. Our research examines the measurement of anticipatory solastalgia: the experience of present distress about expected environmental change.<br>
*Methods*: Our preregistered research uses survey samples from Australia (*n* = 1450) and New Zealand (*n* = 1022) to validate a recently developed five-item Anticipatory Solastalgia Scale (the ANSOS). We also measured participants’ experiences of climate emotions, expectations of the increased severity of climate-related weather disasters, and support for climate policy.<br>
*Results*: The ANSOS fits the data well, is invariant across these two countries, and shows good internal consistency. Supporting convergent validity, the more that participants reported experiencing anticipatory solastalgia, the more intensely they reported feeling negative emotions about climate change. ANSOS scores were higher among those who expected more severe future impacts from climate-related weather disasters, and positively related to support for policies that aim to address climate change.<br>
*Conclusion*: The study adds further evidence for the validity of the anticipatory solastalgia scale; a measure that will facilitate understanding of people's distress responses to the expectations of, and emotional engagement with, environmental threats as the climate changes.
</font>
</details>

<br>

<div style="display: flex">

Cologna, V., Mede, N.G., Berger, S., Besley, J., Brick, C., Joubert, M., …, **Marques, M.D.**, …, & Zwaan, R.A. (2025). Trust in scientists and their role in society across 68 countries. *Nature Human Behaviour*. 
[https://doi.org/10.1038/s41562-024-02090-5](https://www.nature.com/articles/s41562-024-02090-5) [[PDF]](https://www.nature.com/articles/s41562-024-02090-5)<br>
*Impact Factor = 21.4*
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="10.1038/s41562-024-02090-5" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1038/s41562-024-02090-5" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
  <font size="3">Science is crucial for evidence-based decision-making. Public trust in scientists can help decision-makers act based on the best available evidence, especially during crises. However, in recent years the epistemic authority of science has been challenged, causing concerns about low public trust in scientists. We interrogated these concerns with a pre-registered 68-country survey of 71,922 respondents and find that in most countries, most people trust scientists and agree that scientists should engage more in society and policymaking. We find variations between and within countries, which we explain with individual- and country-level variables, including political orientation. While there is no widespread lack of trust in scientists, we cannot discount the concern that lack of trust in scientists by even a small minority may affect considerations of scientific evidence in policymaking. These findings have implications for scientists and policymakers seeking to maintain and increase trust in scientists.
</font>
</details>

<br>

<div style="display: flex">

Mede, N.G., Cologna, V., Berger, S., Besley, J., Brick, C., Joubert, M., …, **Marques, M.D.**, …, & Zwaan, R.A. (2025). Perceptions of science, science communication, and climate change attitudes in 68 countries – the TISP dataset. *Nature Scientific Data*. 
[https://doi.org/10.1038/s41597-024-04100-7](https://doi.org/10.1038/s41597-024-04100-7) [[PDF]](https://osf.io/jktsy)<br>
*Impact Factor = 5.8*
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="10.1038/s41597-024-04100-7" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1038/s41597-024-04100-7" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>Science is integral to society because it can inform individual, government, corporate, and civil society decision-making on issues such as climate change. Yet, public distrust and populist sentiment may challenge the relationship between science and society. To help researchers analyse the science-society nexus across different cultural contexts, we undertook a cross-sectional survey resulting in a dataset of 71,922 participants in 68 countries. The data were collected between November 2022 and August 2023 as part of the global Many Labs study “Trust in Science and Science-Related Populism” (TISP). The questionnaire contained comprehensive measures for individuals’ trust in scientists, science-related populist attitudes, perceptions of the role of science in society, science media use and communication behaviour, attitudes to climate change and support for environmental policies, personality traits, political and religious views and demographic characteristics. Here, we describe the dataset, survey materials and psychometric properties of key variables. We encourage researchers to use this unique dataset for global comparative analyses on public perceptions of science and its role in society and policy-making. 
  <font size="3">
</font>
</details>

<br>

<div style="display: flex">

Hooker, C., **Marques, M.**, Goldwater, M., Degeling, C., & Leask, J. (2024). Values in Risk Communication about Covid-19. In M. Lewis, E. Govender, & K. Holland (Eds.), *Communicating COVID-19: Media, Trust, and Public Engagement (pp. 415–437)*. Springer International Publishing.
[https://doi.org/10.1007/978-3-031-41237-0_21](https://link.springer.com/content/pdf/10.1007/978-3-031-41237-0_21?pdf=chapter%20toc)
<br>
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="10.1007/978-3-031-41237-0" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1007/978-3-031-41237-0_21" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
  <font size="3">This chapter explores how and why risk communication in an outbreak or pandemic context should take account of values. The chapter first briefly discusses the fact that values have been very little explored in risk communication research, despite the close connection between risk perception factors and moral values. We then present evidence showing that values exerted a strong influence values on responses to COVID-19 and the various recommended infection prevention behaviours and public health orders put in place to manage the pandemic. We provide a synthesis of studies that investigated the role of values on COVID-19 related risk perceptions and attitudes using a ‘Moral Foundations’ framework or a ‘Cultural Cognition/ Worldview’ framework. We found that values had a strong but distal influence on public responses to COVID-19, and note the surprisingly positive impacts of reframing infection control messages in values-congruent forms. We consider the possible implications for the design and delivery of outbreak and pandemic risk communication in the future.</font>
</details>

<br>

<div style="display: flex">
**Marques, M.D.**, Critchley, C.R., & Walshe, J. (2015). Attitudes to genetically modified food over time: how trust in organizations and the media cycle predict support. *Public Understanding of Science, 24*, 601-618. [https://doi.org/10.1177/0963662514542372](https://journals.sagepub.com/doi/10.1177/0963662514542372) [[PDF]](https://opal.latrobe.edu.au/ndownloader/files/27388706)<br>
*Impact Factor = 3.702*
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="10.1177/0963662514542372" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1177/0963662514542372" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
  <font size="3">This research examined public opinion toward genetically modified plants and animals for food, and how trust in organizations and media coverage explained attitudes toward these organisms. Nationally representative samples (*N8 = 8821) over 10 years showed Australians were less positive toward genetically modified animals compared to genetically modified plants for food, especially in years where media coverage was high. Structural equation modeling found that positive attitudes toward different genetically modified organisms for food were significantly associated with higher trust in scientists and regulators (e.g. governments), and with lower trust in watchdogs (e.g. environmental movement). Public trust in scientists and watchdogs was a stronger predictor of attitudes toward the use of genetically modified plants for food than animals, but only when media coverage was low. Results are discussed regarding the moral acceptability of genetically modified organisms for food, the media’s role in shaping public opinion, and the role public trust in organizations has on attitudes toward genetically modified organisms.</font>
</details>

<br>

## Vaccination

<div style="display: flex">

Steffens, M.S., Bullivant, B., Kaufman, J., King, C., Danchin, M.,  Hoq, M., & **Marques, M.D.** (2023). Testing persuasive messages about booster doses of COVID-19 vaccines: A randomised controlled trial. *PLoS ONE, 18*(6): e0286799. [https://doi.org/10.1371/journal.pone.0286799](https://doi.org/10.1371/journal.pone.0286799) [[PDF]](https://journals.plos.org/plosone/article/file?id=10.1371/journal.pone.0286799&type=printable)<br>
*Impact Factor = 3.752*
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="10.1371/journal.pone.0286799" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1371/journal.pone.0286799" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
  <font size="3">Introduction: Achieving high COVID-19 vaccine booster coverage is an ongoing global challenge. Health authorities need evidence about effective communication interventions to improve acceptance and uptake. This study aimed to test effects of persuasive messages about COVID-
19 vaccine booster doses on intention to vaccinate amongst eligible adults in Australia. Methods: In this online randomised controlled trial, adult participants received one of four intervention messages or a control message. The control message provided information about booster dose eligibility. Intervention messages added to the control message, each using a different persuasive strategy, including: emphasising personal health benefits of booster doses, community health benefits, non-health benefits, and personal agency in choosing vaccination. After the intervention, participants answered items about COVID-19 booster vaccine intention and beliefs. Intervention groups were compared to the control using tests of two proportions; differences of ≥5 percentage points were deemed clinically significant. A sub-group analysis was conducted among hesitant participants. Results: Of the 487 consenting and randomised participants, 442 (90.8%) completed the experiment and were included in the analysis. Participants viewing messages emphasising non-health benefits had the highest intention compared to those who viewed the control message (percentage point diff: 9.0, 95% CI -0.8, 18.8, *p* = 0.071). Intention was even higher among hesitant individuals in this intervention group compared to the control group (percentage point diff: 15.6, 95% CI -6.0, 37.3, *p* = 0.150). Conversely, intention was lower among hesitant individuals who viewed messages emphasising personal agency compared to the control group (percentage point diff: -10.8, 95% CI -33.0, 11.4, p = 0.330), although evidence in support of these findings is weak. Conclusion: Health authorities should highlight non-health benefits to encourage COVID-19 vaccine booster uptake but use messages emphasising personal agency with caution. These findings can inform communication message development and strategies to improve COVID-19 vaccine booster uptake.

</font>
</details>

<br>

<div style="display: flex">

Abdi, I., Bolsewicz, K., Bullivant, B.,  **Marques, M.D.**, & Steffens, M.S. (2023). Understanding the Factors that Influence Communication about COVID-19 Vaccines with Patients: perspectives of Australian Immunisation Providers. *Vaccine: X*. [https://doi.org/10.1016/j.jvacx.2023.100304](https://www.sciencedirect.com/science/article/pii/S2590136223000451?via%3Dihub) [[PDF]](https://www.sciencedirect.com/science/article/pii/S2590136223000451/pdfft?md5=6e201a1b0b3c0d0d43ad83f04019465f&pid=1-s2.0-S2590136223000451-main.pdf)<br>
*Impact Factor = 3.534*
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="10.1016/j.jvacx.2023.100304" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1016/j.jvacx.2023.100304" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
  <font size="3">Background
COVID-19 immunisation providers have been at the forefront of the pandemic, and their ability to communicate effectively with patients is key to encouraging COVID-19 vaccine acceptance and uptake. This study explored providers’ perspectives on the factors influencing communication with patients about COVID-19 vaccines. Methods: We used an explanatory-sequential mixed-methods approach to conduct the study between December 2021 and March 2022. Phase I involved a cross-sectional survey with immunisation providers in New South Wales (n = 341; 189 general practitioners, 118 nurses and 34 pharmacists), followed by Phase II: semi-structured, in-depth qualitative interviews (n = 19; 10 nurses, 9 pharmacists). We generated descriptive results for the survey. We analysed the qualitative data thematically using an inductive approach.Results: Almost half of survey participants reported communicating often with people who were hesitant about COVID-19 vaccines (49%; 166/341), however, 21% (71/341) reported inadequate time to address concerns during consultations. Interview participants reported communication challenges, including time constraints, difficulties addressing and eliciting patient concerns, and keeping up to date with changing information. Conversely, interview participants reported that easy access to government information resources, time to learn about COVID-19 vaccines proactively, knowing about and being able to use tailored strategies to support Aboriginal and Torres Strait Islander and CALD patients were helpful when communicating with patients. Conclusions: Immunisation providers play an important role in patient vaccine acceptance and uptake. Our findings indicate that whilst providers were largely confident in their interactions with patients, further communication support would strengthen providers’ skills in communicating with patients who have questions and concerns about COVID-19 vaccines.
</font>
</details>

<br>

<div style="display: flex">

Kaufman, J., Steffens, M.S., Hoq, M., King, C., **Marques, M.D.**, Mao, K., Bullivant, B., & Danchin, M. (2023). Effect of persuasive messaging about COVID-19 vaccines for 5- to 11-year-old children on parent intention to vaccinate. *Journal of Paediatrics and Child Health, 59*(4), 686-693. [https://doi.org/10.1111/jpc.16374](https://onlinelibrary.wiley.com/doi/10.1111/jpc.16374) [[PDF]](https://onlinelibrary.wiley.com/doi/10.1111/jpc.16374)<br>
*Impact Factor = 1.954*
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="10.1111/jpc.16374" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1111/jpc.16374" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
  <font size="3">Aim: Uptake of COVID-19 vaccines for children aged 5–11 years old in Australia has plateaued. Persuasive messaging is an efficient and adaptable potential intervention to promote vaccine uptake, but evidence for its effectiveness is varied and dependent on context and cultural values. This study aimed to test persuasive messages to promote COVID-19 vaccines for children in Australia.
Methods: A parallel, online, randomised control experiment was conducted between 14 and 21 January 2022. Participants were Australian parents of a child aged 5–11 years who had not vaccinated their child with a COVID-19 vaccine. After providing demographic details and level of vaccine hesitancy, parents viewed either the control message or one of four intervention texts emphasising (i) personal health benefits; (ii) community health benefits; (iii) non-health benefits; or (iv) personal agency. The primary outcome was parents' intention to vaccinate their child.
Results: The analysis included 463 participants, of whom 58.7% (272/463) were hesitant about COVID-19 vaccines for children. Intention to vaccinate was higher in the community health (7.8%, 95% confidence interval (CI) −5.3% to 21.0%) and non-health (6.9%, 95% CI −6.4% to 20.3%) groups, and lower in the personal agency group (−3.9, 95% CI −17.7 to 9.9) compared to control, but these differences did not reach statistical significance. The effects of the messages among hesitant parents were similar to the overall study population.
Conclusion: Short, text-based messages alone are unlikely to influence parental intention to vaccinate their child with the COVID-19 vaccine. Multiple strategies tailored for the target audience should also be utilised.
</font>
</details>

<br>

<div style="display: flex">

**Marques, M.D.** & Sheel, M. (2023). Addressing the social inequities of vaccination: an imperative to close the gap. *The Lancet Global Health, 11*(2), e173-e174. [https://doi.org/10.1016/S2214-109X(23)00002-5](https://linkinghub.elsevier.com/retrieve/pii/S2214109X23000025) [[PDF]](https://linkinghub.elsevier.com/retrieve/pii/S2214109X23000025)<br>
*Impact Factor = 38.927*
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="10.1016/S2214-109X(23)00002-5" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1016/S2214-109X(23)00002-5" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
  <font size="3">The COVID-19 pandemic has opened fissures along social, political, economic, and health domains. In doing so, the pandemic uncovered the inequities relating to access and acceptance of vaccines within and across countries. In *The Lancet Global Health*, Nicole Bergen and colleagues use a series of large-scale online cross-sectional global surveys to describe how country-level and individual-level indicators of inequality were associated with both vaccine hesitancy and vaccine refusal among unvaccinated people. Leveraging the largest global health survey to date over approximately 2 years (April 23, 2020, to June 25, 2022) across 90 countries, at first glimpse the paper provides a time-sensitive approach to monitoring vaccine demand and uptake consistent with WHO priorities.

</font>
</details>

<br>

<div style="display: flex">

**Marques, M.D.**, Sibley, C.G., Wilson, M.S., Bulbulia, J., Osborne, D., Yogeeswaran, K., Lee, C.H.J., Duck, I.M., Douglas, K.M., & Cichocka, A. (2022). Psychological predictors of COVID-19 vaccination in New Zealand. *New Zealand Journal of Psychology, 51*(1), 10-27. [[PDF]](https://psyarxiv.com/zkj7u/)<br>
*Impact Factor = 0.581*
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="10.31234/osf.io/zkj7u" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.31234/osf.io/zkj7u" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
  <font size="3">Is it possible to predict COVID-19 vaccination status prior to the existence and availability ofCOVID-19 vaccines? Here, we present a logistic model by regressing decisions to vaccinate in late 2021 on lagged sociodemographic, health, social, and political indicators from 2019 ina sample of New Zealand adults aged between 18 and 94 (*Mage* = 52.92, *SD* = 14.10; 62.21% women; *N* = 5324). We explain 31% of the variance in decision making across New Zealand. Significant predictors of being unvaccinated were being younger, more deprived, reporting less satisfaction with general practitioners, lower levels of neuroticism, greater levels of subjective health and meaning in life, higher distrust in science and in the police, lower satisfaction in the government, as well as political conservatism. Additional cross-sectional models specified using the same, and additional COVID-19-specific factors are also presented. These findings reveal that vaccination decisions are neither artefacts of context norchance, but rather can be predicted in advance of the availability of vaccines.</font>
</details>

<br>

<div style="display: flex">

Steffens, M.S., Dunn, A.G., **Marques, M.D.**, Danchin, M., Witteman, H.O., & Leask, J. (2021). Addressing Myths and Vaccine Hesitancy: A Randomized Trial. *Pediatrics, 148*(5), e2020049304. [https://doi.org/10.1542/peds.2020-049304](https://publications.aap.org/pediatrics/article/148/5/e2020049304/181668/Addressing-Myths-and-Vaccine-Hesitancy-A) [[PDF]](https://publications.aap.org/pediatrics/article-pdf/148/5/e2020049304/1228271/peds_2020049304.pdf)<br>
*Impact Factor = 5.417*
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="10.1542/peds.2020-049304" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1542/peds.2020-049304" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
  <font size="3">*OBJECTIVES*: Evidence on repeating vaccination misinformation or "myths" in debunking text is inconclusive; repeating myths may unintentionally increase agreement with myths or help discredit myths. In this study we aimed to compare the effect of repeating vaccination myths and other text-based debunking strategies on parents’ agreement with myths and their intention to vaccinate their children.
*METHODS*: For this online experiment we recruited 788 parents of children aged 0 to 5 years; 454 (58%) completed the study. We compared 3 text-based debunking strategies (repeating myths, posing questions, or making factual statements) and a control. We measured changes in agreement with myths and intention to vaccinate immediately after the intervention and at least 1 week later. The primary analysis compared the change in agreement with vaccination myths from baseline, between groups, at each time point after the intervention.
*RESULTS*: There was no evidence that repeating myths increased agreement with myths compared with the other debunking strategies or the control. Posing questions significantly decreased agreement with myths immediately after the intervention compared with the control (difference: −0.30 points, 99.17% confidence interval: −0.58 to −0.02, P = .004, d = 0.39). There was no evidence of a difference between other debunking strategies or the control at either time point, or on intention to vaccinate.
*CONCLUSIONS*: Debunking strategies that repeat vaccination myths do not appear to be inferior to strategies that do not repeat myths.</font>
</details>

<br>

## Body image

<div style="display: flex">

Jarman, H.K., McLean, S.A., **Marques, M.D.**, Slater, A., Paxton, S.J., & Fuller-Tyszkiewicz, M. (2024). Understanding what drives adolescent social media behaviours: Informing approaches for interventions. *Body Image, 51*, 101793. [https://doi.org/10.1016/j.bodyim.2024.101793](https://www.sciencedirect.com/science/article/pii/S1740144524001153)<br>
*Impact Factor = 6.406*
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="10.1016/j.bodyim.2024.101793" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1016/j.bodyim.2024.101793" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
  <font size="3">While much research has explored the impacts of social media use, less is known about what factors drive use. The present study aimed to examine the relationship between potential drivers of social media use; namely social media literacy, motivations, and internalisation of appearance ideals, and determine whether they work in combination or individually to predict a range of social media use variables over time. Australian adolescent girls (*n* = 704) and boys (*n* = 938) aged 11-16 years completed online surveys at baseline and 6-month follow-up. Bivariate correlations and a series of multiple regressions were performed separately by gender. Results revealed weak associations between drivers and found they uniquely contributed to social media use, though this was dependent on use outcome. Thin- and muscular-internalisation were especially related to appearance-focused use (e.g., social media comparisons) among girls and boys, respectively, and results were largely consistent across gender. These findings have important implications for interventions, whereby multicomponent holistic interventions which focus on social media literacy, internalisation, and motivations may be most appropriate and necessary to modify a range of social media use behaviours among adolescents.   
</font>
</details>

<br>

<div style="display: flex">

**Marques, M.D.**, Paxton, S.J., McLean, S.A., Jarman, H.K., & Sibley, C.G. (2022). A prospective examination of relationships between social media use and body dissatisfaction in a representative sample of adults. *Body Image, 40*, 1-11. [https://doi.org/10.1016/j.bodyim.2021.10.008](https://www.sciencedirect.com/science/article/pii/S1740144521001327) [[PDF]](https://psyarxiv.com/d9r3m/download/?format=pdf)<br>
*Impact Factor = 6.406*
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="10.1016/j.bodyim.2021.10.008" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1016/j.bodyim.2021.10.008" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
  <font size="3">This study examined the temporal sequence of the relationship between social media use and body dissatisfaction in adults. A representative sample of adults (19–92 years old; *M* = 52.83, *SD* = 13.43; 62.02% women, 37.98% men) completed measures of social media use, body dissatisfaction, age, gender, BMI, and demographic variables in 2015, 2016, 2017, 2018 and 2019 (*N* = 6258) in the New Zealand Attitudes and Values Study. In the full sample, higher social media use was significantly associated with higher body dissatisfaction one year later, as was higher body dissatisfaction with higher social media use one year later after controlling for body dissatisfaction/social media use (T-1), gender, age, BMI, ethnicity, relationships status, and SES. Effects were small. The prospective pathway from social media use to body dissatisfaction was significant in all age groups but the reverse relationship was only significant in the middle aged and older groups. Both pathway directions were significant in women but only the pathway from body dissatisfaction to social media use was significant in men. The research has limitations and replication is required. However, findings suggest raising awareness about how to use social media positively across the broad community, not merely in adolescents, may be worthwhile.


</font>
</details>

<br>

<div style="display: flex">

Jarman, H., McLean, S.A., Paxton, S.J., Sibley, C.G., & **Marques, M.D.** (2023). Examination of the temporal sequence between social media use and well-being in a representative sample of adults. *Social Psychiatry and Psychiatric Epidemiology, 58*, 1247-1258. [https://doi.org/10.1007/s00127-022-02363-2](https://link.springer.com/article/10.1007/s00127-022-02363-2) [[PDF]](https://psyarxiv.com/z2yn4/)<br>
*Impact Factor = 4.328*
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="10.1007/s00127-022-02363-2" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1007/s00127-022-02363-2" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
  <font size="3">Given insufficient prospective evidence for relationships between social media use and well-being among adults, the present study examined the temporal sequence between social media use and psychological distress and life satisfaction, and explored age and gender differences. A representative sample of adults (*N* = 7331; 62.4% women; *Mage* = 51.94; *SD* = 13.48; 15–94 years) were surveyed annually across four waves. Cross-lagged panel models demonstrated bidirectional relationships between social media use and well-being. Higher psychological distress and lower life satisfaction predicted higher social media use more strongly than the reverse direction, with effects particularly pronounced for the impact of psychological distress. Although the patterns of findings were relatively consistent across age and gender, results suggested that women and middle- and older-aged adults experience detrimental effects of social media use on well-being, which may drive subsequent increased use of social media. The bidirectional relationships suggest that adults who experience psychological distress or lower life satisfaction may seek to use social media as a way to alleviate poor well-being. However, paradoxically, this maladaptive coping mechanism appears to drive increased social media use which in turn can exacerbate poor well-being. Clinicians should be aware of these bidirectional relationships and work with clients towards replacing ineffective strategies with more helpful coping approaches. As this study used a simplistic measure of social media use, future research should address this limitation and explore nuanced relationships afforded by assessing specific social media activities or exposure to certain types of content.

</font>
</details>

<br>

<div style="display: flex">

Jarman, H.K., Slater, A., McLean, S.A., **Marques, M.D.**, & Paxton, S.J. (2021). The impact of completing body image assessments on adolescents’ body image and engagement in body change strategies: Harmful or harmless? *Body Image, 39*, 131-138. [https://doi.org/10.1016/j.bodyim.2021.07.003](https://www.sciencedirect.com/science/article/pii/S1740144521000991?via%3Dihub)<br>
*Impact Factor = 6.406*
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="10.1016/j.bodyim.2021.07.003" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1016/j.bodyim.2021.07.003" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
  <font size="3">Parents and educators have raised concerns that participating in body image research may cause or increase poor body image and engagement in body change strategies. This quasi-experimental study compared body image and body change strategy outcomes among adolescents who had, and had not, previously been exposed to the same assessment questions 6-months prior (twice- vs once-completers). Comparison was also made between groups who completed an assessment containing only positively worded items or both positive and negative items (positive vs mixed valence). Boys and girls (*N* = 1,532, *Mage* = 13.83, *SD* = 1.18) completed online measures of body dissatisfaction, body appreciation, overvaluation of weight and shape, appearance esteem, and body change strategies. In regression analyses, neither body image nor body change strategies were predicted by group (completion or valence groups), except lower body dissatisfaction and higher body appreciation among twice-completers. Most participants did not experience individual-level change in body image or body change strategies over 6-months. Findings suggest that body image assessments may not put adolescents at risk of poor body image or engagement with body change strategies, however; experimental research is needed. Some improvement in body image may have implications for prospective and prevention research.</font>
</details>

<br>

<div style="display: flex">

Jarman, H. K., **Marques, M.D.**, McLean, S.A., Slater, A., & Paxton, S.J. (2021). Social media, body satisfaction and well-being among adolescents: A mediation model of appearance-ideal internalization and comparison. *Body Image, 36*, 139-148. [https://doi.org/10.1016/j.bodyim.2020.11.005](https://www.sciencedirect.com/science/article/pii/S1740144520304265?via%3Dihub)<br>
*Impact Factor = 6.406*
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="10.1016/j.bodyim.2020.11.005" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1016/j.bodyim.2020.11.005" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
  <font size="3">Despite adolescents’ prolific use of social media, relationships between social media and body satisfaction and well-being are not yet well understood, especially among boys. This study tested a sociocultural model of body image within the context of social media among adolescent boys and girls. Specifically, this study examined whether appearance-ideal internalization and social appearance comparisons mediated relationships between social media engagement (intensity and appearance-focused use) and body satisfaction and subjective well-being. Australian adolescents between 11 and 17 years (*N* = 1,579, *Mage* = 13.45 years, *SD* = 1.15; 55.4 % boys) completed an online survey. Structural equational modelling indicated that only higher appearance-focused social media use was directly associated with lower body satisfaction and well-being. Generally, higher appearance-ideal internalization and comparisons mediated the relationships between higher social media engagement and lower body satisfaction and well-being. Multi-group analyses indicated these relationships were equivalent across gender. Findings supported the proposed model among boys and girls and extend existing theoretical knowledge to encompass male body image and well-being. Interventions which target internalization and comparisons in the context of social media are likely to be valuable in improving body satisfaction and subjective well-being in co-educational settings.</font>
</details>

<br>

<div style="display: flex">

Jarman, H. K., **Marques, M.D.**, McLean, S.A., Slater, A., & Paxton, S.J. (2021). Motivations for Social Media Use: Associations with Social Media Engagement and Body Satisfaction and Well-Being among Adolescents. *Journal of Youth and Adolescence, 50*, 2279-2293. [https://doi.org/10.1007/s10964-020-01390-z](https://link.springer.com/article/10.1007/s10964-020-01390-z)<br>
*Impact Factor = 4.381*
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="10.1007/s10964-020-01390-z" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1007/s10964-020-01390-z" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
  <font size="3">Adolescents are spending considerable time on social media, yet it is unclear whether motivations for social media use drive different forms of social media engagement, and their relationships with body satisfaction and well-being. This study tested a proposed model of the relationships between motivations for social media use, types of social media engagement and body satisfaction and well-being. Responses to an online survey from 1432 Australian adolescents (*Mage* = 13.45 years, *SD* = 1.14, range 11–17; 55.4% boys) were collected. Structural equational modelling indicates excellent model fit. Specifically, motivations for social media use (information sharing, passing time, escapism, social interaction, social capital and appearance feedback) were associated with engagement (intensity, photo-based use, active use, passive use and liking use) and revealed mixed associations with body satisfaction and well-being. The findings support the importance of considering motivations for social media use in future research.</font>
</details>

<br>

<div style="display: flex">

Jarman, H. K., McLean, S.A., Slater, A., **Marques, M.D.**, & Paxton, S.J. (2024). Direct and indirect relationships between social media use and body satisfaction: A prospective study among adolescent boys and girls. *New Media and Society. 26*(1), 292-312. [https://doi.org/10.1177/14614448211058468](https://journals.sagepub.com/doi/10.1177/14614448211058468)<br>
*Impact Factor = 8.061*
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="10.1177/14614448211058468" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1177/14614448211058468" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
  <font size="3">Cross-sectional research suggests a small, inverse association between social media use and body satisfaction. However, less is known regarding prospective, bidirectional, or mediating effects. In line with sociocultural theory, this study used a three-wave design to examine direct and indirect effects between social media use and body satisfaction, via thin-ideal and muscular-ideal internalisation and social comparisons. Adolescents (*n* = 1911; *Mage* = 14.27, *SD* = 1.08) were invited to complete three surveys over 1 year. Cross-lagged panel models indicated acceptable fit for two social media use operationalisations, with better fit statistics for the appearance-focused use rather than photo-based activities model. Despite largely no direct effects, indirect effects were found. Social comparisons mediated the relationships over time, whereby higher social media use predicted higher comparisons, which predicted lower body satisfaction. The reverse direction was also found. Gender invariance indicates that prevention aimed at reducing comparisons may be suitable for boys and girls.
</font>
</details>

<br>

<div style="display: flex">

Rodgers, R.F., Mclean, S.A., Gordon, C.S., Slater, A., **Marques, M.D.**, Jarman, H.K., & Paxton, S.J. (online 9 September 2020). Development and Validation of the Motivations for Social Media Use Scale (MSMU) Among Adolescents. *Adolescent Research Review, 6*, 425-435.
 [https://doi.org/10.1007/s40894-020-00139-w](https://link.springer.com/article/10.1007/s40894-020-00139-w)<br>
*Impact Factor = 5.052*
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="10.1007/s40894-020-00139-w" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1007/s40894-020-00139-w" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
  <font size="3">Theoretical accounts of the relationship between social media use and body image among adolescents have highlighted motivations as an important factor. However, motivations for social media use has received little attention in extant research in the area of body image. The aim of this study was therefore to develop a measure of motivations for social media use among adolescents, with a focus on appearance motivations. Data from 770 adolescents (49% female), mean (SD) age = 12.76 (0.74) were used to examine the psychometric properties of the new Motivations for Social Media Use scale (MSMU). Exploratory and confirmatory factor analyses revealed a four-factor structure including Connection, Popularity, Appearance, and Values and Interests subscales. All subscales revealed acceptable internal reliability, and convergent validity with internalization of appearance ideals, self-esteem, and social media use. The MSMU is a useful tool for assessing appearance motivations for social media use among adolescent girls and boys.</font>
</details>

<br>

<div style="display: flex">

Rodgers, R.F., McLean, S.A., **Marques, M.**, Dunstan, C., & Paxton, S.J. (2016). Trajectories of body dissatisfaction and dietary restriction in early adolescent girls: a Latent Class Growth Analysis. *Journal of Youth and Adolescence, 45*, 1664-1677. [https://doi.org/10.1007/s10964-015-0356-3](https://link.springer.com/article/10.1007/s10964-015-0356-3)<br>
*Impact Factor = 3.247*
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="10.1007/s10964-015-0356-3" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1007/s10964-015-0356-3" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
  <font size="3">Clarifying the trajectories of body image and eating concerns in adolescents is critical. We examined longitudinal patterns of development of body dissatisfaction and dietary restriction among early adolescent girls within a sociocultural framework. A sample of 259 school girls (*Mage* = 12.76 years, *SD* = 0.44) reported on sociocultural influences, body dissatisfaction and dietary restriction at baseline, 8, and 14 months. A subsample provided height and weight. Analyses identified four trajectories of body dissatisfaction: low, moderate-increasing, moderate-decreasing, and high. Three trajectories of dietary restriction emerged: low, moderate, and high. Baseline and 8-month sociocultural variables and BMI differed between the trajectories. A subgroup of girls displays high levels of body image and eating concerns by early adolescence. Sociocultural variables influence these trajectories.</font>
</details>

<br>

<div style="display: flex">

McLean S.A., Wertheim E.H., **Marques, M.D.**, & Paxton S.J. (2019). Dismantling prevention: Comparison of outcomes following media literacy and appearance comparison modules in a randomised controlled trial. *Journal of Health Psychology, 24*, 761-776.
 [https://doi.org/10.1177/1359105316678668](https://journals.sagepub.com/doi/10.1177/1359105316678668) [[PDF]](https://opal.latrobe.edu.au/articles/journal_contribution/Dismantling_prevention_Comparison_of_outcomes_following_media_literacy_and_appearance_comparison_modules_in_a_randomised_controlled_trial/13653317) <br>
*Impact Factor = 3.789*
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="10.1177/1359105316678668" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1177/1359105316678668" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
  <font size="3">A dismantling study of body dissatisfaction prevention was conducted. Adolescent girls (*N* = 260) were randomly allocated to a media literacy (Happy Being Me – Media Literacy) or appearance comparison (Happy Being Me – Appearance Comparison) intervention or healthy eating behaviour control (Happy Being Me – Healthy Eating Behaviour) condition. In the Happy Being Me – Appearance Comparison condition, improvements from baseline to post-programme and follow-up for upward appearance comparison and fear of negative appearance evaluation were observed. In the Happy Being Me – Media Literacy condition, improvements were observed from baseline to post-programme for upward appearance comparison and realism scepticism. Findings were similar in a high-risk subsample and overall are moderately supportive of appearance comparison-based interventions, but less supportive of a stand-alone media literacy intervention.</font>
</details>

<br>

## Other publications

<div style="display: flex">

Clarke, E.J.R., Eckerle, F., Kerr, J.R., Hill, S., Ling, M., **Marques, M.D.**, Williams, M.N. (2025). Extremism at the centre: Uncovering political diversity amongst midpoint responders on the left-right self-placement item. *Political Psychology*. 
[http://doi.org/10.1111/pops.70082](http://doi.org/10.1111/pops.70082)<br>
*Impact Factor = 3.5*
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="10.1111/pops.70082" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1111/pops.70082" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
  <font size="3">The midpoint of the left-right self-placement item is the most populated of all response options. While genuinely-centrist responders opt to self-place there, it is also a convenient response option for those that cannot easily fit their politics to the left-right spectrum. Those with populist attitudes may also see the midpoint as an appropriate self-placement option, due to the thin-centred nature of populist ideology. In support of this, midpoint responders score similarly to the extreme ends of the spectrum on variables related to political system attitudes, including conspiracy beliefs and institutional trust, resulting in W-shaped relationships. Our research investigated the extent to which midpoint bumps exist across common political issues and political system attitudes, and whether subgroups of populist midpoint responders explain them. Using data from the Australian Election Study (*N* = 2179) and the American National Election Study (*N* = 8280), we found W- and M-shaped polynomial relationships primarily on attitudes towards the political system and toward immigrants. We then conducted Latent Profile Analyses on midpoint responders, using these items, finding at least one profile in each sample that represented a response pattern indicative of populist belief strands.
</font>
</details>

<br>

<div style="display: flex">

Austin, D.E.J., **Marques, M.D.**, & Stukas, A.A. (2024). Anti-Egalitarianism Motivates Denial of Male Privilege. *Analyses of Social Issues and Public Policy, 24*(3), 1017-1031. 
[https://doi.org/10.1111/asap.12424](https://spssi.onlinelibrary.wiley.com/doi/10.1111/asap.12424)<br>
*Impact Factor = 1.8*
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="10.1111/asap.12424" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1111/asap.12424" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
  <font size="3">Men are privileged economically, politically, and socially, yet some deny this. Previous research suggests that denial of privilege can help to manage the discomfort associated with a privileged identity, but we propose that it serves primarily to preserve privilege. In two preregistered studies (*N*total = 911 Australian participants) we show that denial of male privilege is not unique to men, and that it is strongly predicted by anti-egalitarianism, even when controlling for gender and other variables known to predict attitudes towards inequality (facets of right-wing authoritarianism and social dominance orientation). In Study 1, a multiple regression model accounted for 59% of the variability in reported male privilege awareness, with anti-egalitarianism contributing 47% of the explanatory power. In Study 2, the explanatory power of anti-egalitarianism was more modest (26%), and similar to that of gender (27%), and both also positively predicted claims of female privilege. This suggests that rather than simply reflecting unawareness of male privilege or being a way to manage a privileged identity, denying the existence of male privilege and claiming that women are privileged helps to preserve gender inequality by presenting it as a just result of meritocracy.
</font>
</details>

<br>

<div style="display: flex">

Kaltenegger, H.C., **Marques, M.D.**, Becker, L., Rohleder, N., Nowak, D., Wright, B.J., Weigl, M. (2024). Prospective associations of technostress at work, burnout symptoms, hair cortisol, and chronic low-grade inflammation. *Brain, Behavior, and Immunity, 117*, 320-329. 
[https://doi.org/10.1016/j.bbi.2024.01.222](https://doi.org/10.1016/j.bbi.2024.01.222)<br>
*Impact Factor = 19.227*
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="10.1016/j.bbi.2024.01.222" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1016/j.bbi.2024.01.222" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
  <font size="3">*Background*. Working conditions in the age of digitalization harbor risks for chronic stress and burnout. However, real-world investigations into biological effects of technostress, that is stress in the context of digital technology use, are sparse. This study prospectively assessed associations between technostress, general work stress, burnout symptoms, hair cortisol, and chronic low-grade inflammation. *Methods*. Hospital employees (*N*=238, 182 females, *Mage*=28.5 years) participated in a prospective cohort study with two follow-ups six months apart (T2, T3). Participants answered standardized questionnaires on general job strain (job demand-control ratio), technostressors (work interruptions, multitasking, information overload), burnout symptoms (exhaustion, mental distance), and relevant confounders. Moreover, they provided capillary blood samples for C-reactive protein (CRP) and hair strands for hair cortisol concentration (HCC) analysis. Structural equation modelling was performed. *Results*. The factorial structure of survey measures was confirmed. Burnout symptoms (MT2=2.17, MT3=2.33) and HCC (*MT2*=4.79, *MT3*=9.56; pg/mg) increased over time, CRP did not (*MT2*=1.15, *MT3*=1.21; mg/L). Adjusted path models showed that technostress was negatively associated with HCC (*β*=-0.16, *p*=.003), but not with burnout and CRP. General work stress in contrast, was not significantly associated with burnout, HCC or CRP. Furthermore, there were reciprocal effects of CRP on HCC (*β*=0.28, *p*=.001) and of HCC on CRP (*β*=-0.10, *p*≤.001). Associations were robust in additional analyses including further confounders. *Conclusion*. This is the first study on prospective effects of technostress on employees’ endocrine and inflammatory systems. Results suggest differential effects of technostress on the hypothalamic-pituitary-adrenocortical axis activity. Given its key role for long-term health, the findings have important implications for occupational health and safety in digitalized work environments. 
</font>
</details>

<br>

<div style="display: flex">

**Marques, M.D.** (2023). The Tall Poppy Syndrome, Heroism, and Villainy. *Encyclopedia of Heroism Studies*. 
[https://doi.org/10.1007/978-3-031-17125-3_441-1](https://link.springer.com/referenceworkentry/10.1007/978-3-031-17125-3_441-1)   <br>[or email me for a copy](mailto:m.marques@latrobe.edu.au?subject=The Tall Poppy Syndrome, Heroism, and Villainy chapter in Encyclopedia of Heroism Studies)
<br>
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="10.1007/978-3-031-17125-3" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1007/978-3-031-17125-3_441-1" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<details>
  <summary>
  <font size="3">Definition</font>
  </summary>
  
  <font size="3">The tall poppy is an individual who holds high status or rank either due to their achievements or by virtue of legal or quasi legal prescriptions. The tall poppy syndrome is a cultural phenomenon where people want to see or act to denigrate a high status individual.
</font>
</details>

<br>

<div style="display: flex">

**Marques, M.D.**, Feather, N.T., Austin, D.E.J., & Sibley, C.G. (2022). Attitudes towards favouring the fall of Tall Poppies: The role of social dominance orientation, authoritarianism, political ideologies, and self-esteem. *The Journal of Social Psychology, 162*(5), 640-653. [https://doi.org/10.1080/00224545.2021.1944034](https://www.tandfonline.com/doi/full/10.1080/00224545.2021.1944034) [[PDF]](https://psyarxiv.com/bzexa/)<br>
*Impact Factor = 2.712*
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="10.1080/00224545.2021.1944034" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1080/00224545.2021.1944034" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
  <font size="3">Individuals occupying high-status positions are sometimes victims of the tall poppy syndrome where people want to see them cut down to size. These attitudes reflect a tension between achievement, authority, and equality. In a pre-registered study (Study 1: *N* = 47,951), and a replication (Study 2: *N* = 5,569), of two representative New Zealand samples we investigated how social dominance orientation, right-wing authoritarianism, political ideologies and self-esteem predicted favoring the fall of the tall poppy. Novel findings showed individuals high in social dominance orientation favored the fall of the tall poppy. In both studies, high authoritarian aggression and submission, and low conventionalism (in Study 1 only) were also associated with negative tall poppy attitudes. So too were individuals with lower self-esteem and who were less conservative in their political ideology. These findings advance our understanding of how group-based hierarchy and inequality relate to attitudes toward individuals in high-status positions.</font>
</details>

<br>

<div style="display: flex">

Hall, A., McLennan, J., **Marques, M.D.**, & Bearman, C. (2022). Conceptualising and measuring householder bushfire (wildfire) risk perception: the Householder Bushfire Risk Perception Scale (HBRPS-4). *International Journal of Disaster Risk Reduction, 67*, 102667.  [https://doi.org/10.1016/j.ijdrr.2021.102667](https://www.sciencedirect.com/science/article/pii/S2212420921006282?via%3Dihub)<br>
*Impact Factor = 2.896*
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="10.1016/j.ijdrr.2021.102667" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1016/j.ijdrr.2021.102667" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
  <font size="3">With increasing numbers of householders living in high bushfire (wildfire) risk areas, there is a need to better understand householders' bushfire risk perceptions. In the community bushfire safety research literature, there appears to be no consensus on how best to conceptualise and measure householders' bushfire risk perceptions. The aim of this research was to investigate the concept of bushfire risk perception and its measurement, and to develop a brief, reliable and valid measure of householders’ bushfire risk perceptions. Following a review of 26 studies, a four-item householder bushfire risk perception scale (HBRPS-4) was developed. Analysis of responses to an online survey of 375 householders indicated that the measure had high internal consistency (α = 0.93). There was evidence of: construct validity, concurrent convergent criterion validity (|*r*| range 0.21–0.58), and concurrent discriminant criterion validity (*r* ≤ 0.15). A supplementary study with 27 participants found a high level of test-retest reliability over a six-week period (*r* = 0.95). It is suggested that householder bushfire risk perception can be construed as a fuzzy concept, incorporating three risk perception elements (probability, consequences, concern) whose meaning boundaries are not well-differentiated. The HBRPS-4 appears to hold promise of being a useful measure for community bushfire safety research.</font>
</details>

<br>

<div style="display: flex">

**Marques, M.D.**, Wright, B.J., Lee, C.H.J., & Sibley, C.G. (2021). Increased sleep predicts annual decreases in psychological distress: Results from a six-year longitudinal panel sample. *Sleep Health, 78*(3), 368-374. [https://doi.org/10.1016/j.sleh.2020.12.005](https://www.sciencedirect.com/science/article/abs/pii/S2352721820303259?via%3Dihub) [[PDF]](https://psyarxiv.com/brmyp/)<br>
*Impact Factor = 4.450*
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="10.1016/j.sleh.2020.12.005" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1016/j.sleh.2020.12.005" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
  <font size="3">*Objective*: To investigate the annual temporal ordering of sleep quantity and psychological distress, separating between-person stability from within-person change.
  *Design*: Random-intercepts cross-lagged panel model using six annual waves of longitudinal data from the New Zealand Attitudes Values Study postal questionnaire.Participants: New Zealand Attitudes Values Study respondents in 2013, 2014, 2015, 2016, 2017, and 2018 (Ns = 17,890; 15,757; 13,904; 21,849; 17,031; and 47,462).
  *Measurements*: Participants were asked, “During the past month, on average, how many hours of actual sleep did you get per night?” and responded to the K6 psychological distress scale each year. They also reported their demographic characteristics.
  *Results*: Identified longitudinal associations between sleep duration and psychological distress in a traditional cross-lagged panel model were mostly attributable to the stability of the between-person differences in sleep duration and psychological distress. We provide evidence to suggest that increased sleep duration as indicated over a short period of time (i.e.,one month) predicted lower within-person levels of psychological distress the following year.Psychological distress did not predict sleep duration, in contrast.
  *Conclusions*: Our analyses suggest that sleep duration in this sample of New Zealanders precedes psychological distress. This is significant given the propensity for short sleep in this sample and issues of poor mental health and short sleep among low SES indigenous membersof this community. The promotion of adequate sleep duration may yield positive gains in psychological well-being</font>
</details>

<br>

<div style="display: flex">

Piantella, S., Dragano, N., **Marques, M.D.**, McDonald, S.J., & Wright, B.J. (December 2021). Prospective increases in depression symptoms and markers of inflammation increase coronary heart disease risk- The Whitehall II cohort study. *Journal of Psychosomatic Research, 151*, 110657. doi: 
 [https://doi.org/10.1016/j.jpsychores.2021.110657](https://www.sciencedirect.com/science/article/pii/S0022399921003020?via%3Dihub)<br>
*Impact Factor = 3.006*
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="10.1016/j.jpsychores.2021.110657" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1016/j.jpsychores.2021.110657" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
  <font size="3">*OBJECTIVES*: Stress, inflammation, and depression are associated to coronary heart disease (CHD). However, how these constructs collectively contribute to CHD incidence is not well understood. For the first time, this study explored the concurrent relationship between workplace stress, depression symptomology and levels of low-grade inflammation with future CHD incidence.
*METHODS*: Data from the 5-year intervals at phase 5, 7, and 9 of the Whitehall II study (*N* = 8348, *Mage* = 56) provided measures of workplace stress, depression symptomology, inflammation (interleukin-6, C-reactive protein, fibrinogen), and CHD incidence. The proposed stress-inflammation-depression-CHD pathway was assessed with a longitudinal design incorporating a structural equation model (SEM) that measured if changes in stress, depression, and inflammation between phase 5 to phase 7 predicted first-time CHD events between phases 7 and 9.
*RESULTS*: The SEM empirically supported this proposed pathway and demonstrated excellent model fit, *χ* (72) = 3582.959, *p* < .001, *CFI* = 0.896, *RMSEA* = 0.076 (CI90 = 0.074, 0.079), while depression symptoms mediated the association between workplace stress and CHD incidence, *B* = 0.003 (CI90 = 0.001, 0.004). Further, survival analysis indicated that individuals with higher mean scores (across phases) of depression symptoms or fibrinogen levels were more likely to experience a first time CHD event.
*CONCLUSIONS*: Increases in depression symptoms and fibrinogen levels may be good indicators of future CHD morbidity among older employees. Future research is encouraged to monitor negative affective states and the potential use of biobehavioural options to reduce depression and inflammation that may mitigate CHD risk.</font>
</details>

<br>


<div style="display: flex">

McLennan, J., **Marques, M.D.**, & Every, D. (2020). Conceptualising and measuring psychological preparedness for disaster: The Psychological Preparedness for Disaster Threat Scale. *Natural Hazards, 101*, 297–307. [https://doi.org/10.1007/s11069-020-03866-4](https://link.springer.com/article/10.1007/s11069-020-03866-4)<br>
*Impact Factor = 3.656*
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="10.1007/s11069-020-03866-4" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1007/s11069-020-03866-4" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
  <font size="3">Most research on household disaster preparedness has focussed on physical, or material, preparation. Recently, researchers have turned attention to investigating psychological, or mental, preparedness for disasters. Reviews suggest that psychological preparedness comprises two broad mental dimensions or domains: a mostly cognitive aspect directed at the threat, involving knowledge of the threat environment and adaptive responses; and a mostly affective aspect involving self-awareness and emotional self-control. We located eight self-report measures of psychological preparedness, of which only three evidenced good psychometric properties. Of these, only the Psychological Preparedness for Disaster Threat Scale (PPDTS) developed by Zulch et al. (Psychological preparedness for natural disasters, 2012) seemed suitable for investigating psychological preparedness for disaster events in general in English-speaking contexts. A confirmatory factor analysis of data from a survey of 1253 Australian residents replicated the findings reported by Zulch et al. that the measure comprised two sub-scales: a 10-item Knowledge and Management sub-scale, and an 8-item Anticipation, Awareness and Management sub-scale. Evidence of both concurrent convergent and discriminant validity of the measure was found. The PPDTS appears to be a psychometrically sound self-report measure of householder psychological preparedness for a disaster event.

</font>
</details>

<br>

<div style="display: flex">

Petrovic, K.P., Stukas, A.A., & **Marques, M.D.** (2020). Religiosity, motivations and volunteering: A test of two theories of religious prosociality. *Journal of Theoretical Social Psychology, 4*, 157-168. [https://doi.org/10.1002/jts5.68](https://onlinelibrary.wiley.com/doi/10.1002/jts5.68) [[PDF]](https://opal.latrobe.edu.au/ndownloader/files/27374003)<br>
*Impact Factor = 1.341*
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="10.1002/jts5.68" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1002/jts5.68" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
  <font size="3">Although it is well-established that religious individuals tend to volunteer more than the non-religious, few studies have examined motivations to volunteer as a potential explanation for this relationship. The present research takes a functional approach to examine whether religiosity drives volunteerism by promoting certain motivations for volunteering. Two common theories of religious prosociality are considered: (1) religious belief increases volunteering through internalized prosocial values, and (2) religious service attendance increases volunteering by fostering social relationships, hence increasing social reasons for volunteering. In two studies, Values-based and Social-based motivations to volunteer are tested as mediators in the relationship between religiosity (both belief and service attendance) and volunteering. Study 1 used a predominantly university student sample (*N* = 130) to predict volunteering intentions, whereas Study 2 employed an Australian community sample (*N* = 772) to predict self-reported volunteer hours. Both studies show consistent findings that the Values motive mediated the relationship between religious belief and volunteering, whereas the Social motive did not mediate the relationship between religious service attendance and volunteering. We find support for the theory that religious beliefs boost volunteerism by promoting humanistic reasons for volunteering.</font>
</details>

<br>

<div style="display: flex">

**Marques, M.D.**, Elphinstone B., Critchley C.R., & Eigenberger, M.E. (2017). A brief scale for measuring Anti-Intellectualism. *Personality and Individual Differences, 114*, 167-174. [https://doi.org/10.1016/j.paid.2017.04.001](https://www.sciencedirect.com/science/article/abs/pii/S0191886917302507?via%3Dihub) [[PDF]](https://opal.latrobe.edu.au/ndownloader/files/27374003)<br>
*Impact Factor = 3.004*
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="10.1016/j.paid.2017.04.001" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1016/j.paid.2017.04.001" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
  <font size="3">This paper describes the development of a brief scale to measure anti-intellectualism, the degree to which one experiences either positive or negative affect while engaged in epistemic activities such as conceptual integration. Using seven samples, the study examined several psychometric components of the measure, including equivalency across community and student/convenience populations, temporal stability, and indications of different forms of validity. The scale was designed to be a brief, reliable and valid measure of individual differences in the degree to which individuals value affect-reinforced need for intellectual engagement. These results suggest that the Anti-Intellectualism Scale may provide a useful tool for the examination of differences in the desire to engage in intellectually challenging activities, and subsequent outcomes such as vocational interest, academic achievement, and democratic citizenship.</font>
</details>

<br>

<div style="display: flex">

Honeyman K.L., Stukas A.A., & **Marques M.D.** (2016). Human trafficking: factors that influence willingness to combat the issue. *Journal of Applied Social Psychology, 46*, 529-543. [https://doi.org/10.1111/jasp.12381](https://onlinelibrary.wiley.com/doi/10.1111/jasp.12381) [[PDF]](https://opal.latrobe.edu.au/ndownloader/files/27389102)<br>
*Impact Factor = 2.122*
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="10.1111/jasp.12381" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1111/jasp.12381" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
  <font size="3">Human trafficking involves severe violations of human rights and social action is required to combat it. Past research has identified emotional reactions to victims of trafficking, as well as the perceived cost and efficacy of actions, as significant predictors of willingness to get involved. We surveyed 216 Australians (70% female) to assess their perceptions of sex and labor trafficking and actions to reduce them. Results demonstrated that women reported greater personal distress (but not empathy) for victims than men, which was associated with greater willingness to take action. Women also perceived available actions to be more efficacious than men, which predicted willingness, while perceived cost of actions did not. Implications for promoting social action to reduce human trafficking are discussed.</font>
</details>

<br>

<div style="display: flex">
Kashima, E.S., Beatson, R., Branchflower, S., Kaufmann, L., & **Marques, M.D.** (2014). Mortality salience and cultural cringe: The Australian way of responding to thoughts of death. *Journal of Cross-Cultural Psychology, 45*, 1534-1548. [https://doi.org/10.1177/0022022114543521](https://journals.sagepub.com/doi/10.1177/0963662514542372)<br>
*Impact Factor = 2.577*
</div>
<div style="display: flex; justify-content: space-between; width: 140px;">

<div data-badge-popover="right" data-badge-type="donut" data-doi="10.1177/0022022114543521" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1177/0022022114543521" data-legend="hover-right" data-style="small_circle" data-hide-zero-citations="true"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
</div>

<details>
  <summary>
  <font size="3">Abstract</font>
  </summary>
  
  <font size="3">Terror Management Theory predicts that mortality salience (MS) instigates cultural worldview defenses, especially among individuals with lower self-esteem. That MS intensifies positive evaluations of pro-U.S. essay authors, and negative evaluations of anti-U.S. essay authors have been documented as supportive evidence. However, the evidence to date may have been limited to where praising for the former and rejection of the latter authors is consistent with a shared cultural script and thus normative. In the case of Australian people, the cultural script of cringe prescribes them to evaluate their country modestly and to reject high praise of their country. We therefore predicted that MS (vs. control) should lead Australians, with low self-esteem in particular, to evaluate pro-Australia essay authors less positively while not affecting their evaluations of anti-Australia essay authors. Results from two studies were consistent with this prediction. It is important to distinguish MS effects on adherence to cultural norms from those on reaffirming collective self-esteem, and to consider relevant cultural scripts when interpreting evidence for worldview defenses.</font>
</details>
